### ISSUE TITLE
Infomration is spelled incorrectly

### ISSUE THREAD

**Issue by hbhrugubanda** [amhammett/ansible-learning#1]
An instance of "information" in the Readme is spelled as "infomration"

**Comment by hbhrugubanda** [comment]
I don't have access to branch and create a PR to correct this

**Comment by haydargokmen** [comment]
Updated, here is the PR

**Comment by hbhrugubanda** [comment]
Your PR looks good. Merge away

**Comment by amhammett** [comment]
Thanks for looking and the fix!

#2 has been merged
